library("bnclassify")
library("dplyr")
library("gRain")
library("caret")

train_for_tan = read.csv("E:/train_for_tan43.csv", header = TRUE)
df <- mutate_if(train_for_tan, is.integer, as.factor)
naive = nb('Response', df)
naive = lp(naive, df, smooth = 0.01)
p = predict(naive, df, prob=TRUE)
cv(naive, df, k=10)
tn = tan_cl('Response', df)
tn = lp(tn, df, smooth=0.01)
tnp = predict(tn, df, prob=TRUE)
cv(tn, df, k=10)
plot(tn)
p_ = predict(naive, df, prob = TRUE)
write.csv(p_, file='E:nbupsampled_nb10_pred.csv')
testdf = read.csv("E:/test.csv", header = TRUE)
testdf = subset(testdf, select = -c(X))
testdf2 <- mutate_if(testdf, is.numeric, as.factor)
p_ = predict(tn, testdf2, prob = TRUE)
write.csv(p_, file='E:nbtest_pred.csv')
